apiVersion: apps/v1
kind: Deployment
metadata:
  name: oi-was
  namespace: oi
spec:
  replicas: 2
  selector:
    matchLabels: { app: oi-was }
  template:
    metadata:
      labels: { app: oi-was }
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: app
          image: ghcr.io/baninbanryenog/oi-was:1a0ba4e
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet: { path: "/", port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 8000 }
            initialDelaySeconds: 20
            periodSeconds: 10
