apiVersion: apps/v1
kind: Deployment
metadata:
  name: oi-was
  namespace: oi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oi-was
  template:
    metadata:
      labels:
        app: oi-was
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: app
          image: ghcr.io/baninbanryenog/oi-was:cb03e83
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
