apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: oi
spec:
  replicas: 1
  selector: { matchLabels: { app: mysql } }
  template:
    metadata: { labels: { app: mysql } }
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - { name: MYSQL_ROOT_PASSWORD, value: rootpass }
            - { name: MYSQL_DATABASE, value: oi }
            - { name: MYSQL_USER, value: oiuser }
            - { name: MYSQL_PASSWORD, value: oipass }
          ports: [{ containerPort: 3306 }]
          args: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: oi
spec:
  selector: { app: mysql }
  ports:
    - port: 3306
      targetPort: 3306
